[gcp]
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgb8r+VxtyOWvG
Z39l8GAeiOuwJUCfk9DhbbzxMsxI2Gc1gkIzGiGUkLIL7B7tOnmhibfXzb74HXnB
hMUkx95VHveb5OpiBGuIJCqypFFxPtSBF8OmyVTqjtDABQyREW3v5fxnUirljNiX
0s8dEQGABGBLVENj96KRBAFlojy0kFz8kEXzaRrA7kKNsmuwt3Jj5pQaAniHuuMD
Rco/LyM2SIrv3cozjdi0XTgxZerc093BRNABSMlu1V4zaV9/kXHnzmA4RdIePaHG
9j9XPpJ5DL9fh69TbwEQ+oQBY78ZtC1Kr2aCGuWBie7c7eRYZ5tvRxF7e6HVZWgE
E0+KWXM3AgMBAAECggEAPPI66uOsSXgGuRgYDWGDIhZhcki0g+pjLz/Axt/FOub6
ThltjHwgxY8yE9Ve6j+MdREcBZ7jLN4For4NJivHCg75gP81CocjUlRq4/IH/j0f
/OpKKNHSsEgQhOFmJLW6TafQem98XDdlEEfE5gXPzBHdgsA/2Xn5B5296h33cZ/L
OjhJjQOAb/lXw2jqr76IBeqIZQbiUvdc3BHLWWpYT9zi9AnQ6XfrUQLrxEQt5QdD
bdp2XSq37QU/UwGlphFM6baOiNavz5SWRv5w0nkKcvfvQTPTcoxN/g94Fjy4Xger
9/84xWJWS0bIjUZoRM6zXJhxBol4UQrvSMb8sPSmAQKBgQDbnHWMlpj6CbYoVMKu
jnt6FCS2E5X6YcfX0n7X3kbsFozEaxEvJbB/1VFaWAkD1wAUk/ayrFd3bKZHsZpr
025NXkg7jnZc+/v0LmRImUw+KKkj8w1KNF6z0rtZibXkWto/t/hGKyLGjTIp2IC6
LMPCtaUlwLs35XWs0dsnGcTD4wKBgQC7BUAyZeRj+G9NlmEdntlXCCmzFrgZMYfw
qrQdXmFzun9dtQnCAz6IKZgTFMG70ptueK3TDYcmVHmnsn9lxeVqWMoBylUggPo2
2tMzHPC3O/arSeVz3O1qwD9EZ1d+Vjad8lp9vgMGIsTPVzFipswSMUjwBIPhcDto
uzQnNNg7nQKBgFGJ5Qc+/yuPIYgV+HaxRl1MT1kfKoddeMLET/48dF7B/KANFMNJ
nh/Ihz0hBK/dSxVY3rb2UD9yIsbpxWkVhpXJVM5wFbhugtzlwKxH5swJcst7Ocr8
aNEhhBg5jkRsCy6vUspSx8WqtR5eWWVGq6SGpvu+dITLeIajIFiDM9B7AoGATZ3l
QcVV30OY9etmTMPDUcJ6g+/24cXTtEc0T0f/S+dnur1K2nE8P4h7q9eee9PxXAzL
n17q6zZ98uI6y0MxbkyBMfMGF2JP9folUv48zN8fBYG6r7ZN9lLpLvtwrWccbbrK
YYs9eAtwANkgDuBIq3g23B4TmblZfqLLB0aAQ2UCgYEAlLz58pdmJUxOan0h0osf
4jvoK+JSFWZVXgkwCbc9G6IBacrULFvUwOUU4ZQW2Ua6zdZcBEsIDAYxVO2gq1te
t26265g5VCvqATx8HujCfhsNdRSGp7dhrAi5YQnScp32OZ6cPfH5OlxG+6H2OHXJ
kTSR4rnBLoBh0qIpR8bqrCc=
-----END PRIVATE KEY-----
"""
